# Generated by Django 4.1.3 on 2022-11-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=40)),
                ('student_class', models.CharField(max_length=10)),
                ('student_email', models.CharField(max_length=30)),
            ],
        ),
    ]
