# Generated by Django 3.2.5 on 2022-12-21 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('profession', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=100)),
                ('group', models.CharField(choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Business Studies', 'Business Studies')], max_length=100)),
                ('subject_science', multiselectfield.db.fields.MultiSelectField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Applied Physics', 'Applied Physics'), ('ICT', 'ICT'), ('Applied Math', 'Applied Math')], max_length=200)),
                ('subject_arts', multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('BGS', 'BGS')], max_length=200)),
                ('subject_business', multiselectfield.db.fields.MultiSelectField(choices=[('Finance', 'Finance'), ('Accounting', 'Accounting'), ('Economics', 'Economics')], max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('biodata', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
