# Generated by Django 3.2.5 on 2022-12-21 17:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='subject_arts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Bangla', 'Bangla'), ('English', 'English'), ('BGS', 'BGS')], max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='subject_business',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Finance', 'Finance'), ('Accounting', 'Accounting'), ('Economics', 'Economics')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='subject_science',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Applied Physics', 'Applied Physics'), ('ICT', 'ICT'), ('Applied Math', 'Applied Math')], max_length=200, null=True),
        ),
    ]
