# Generated by Django 3.2.5 on 2022-12-21 19:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221221_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='subject_business',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Finance', 'Finance'), ('Accounting', 'Accounting'), ('Economics', 'Economics')], max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='subject_science',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Applied Physics', 'Applied Physics'), ('ICT', 'ICT'), ('Applied Math', 'Applied Math')], max_length=200),
        ),
    ]
