# Generated by Django 3.2.5 on 2022-12-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=40)),
                ('owner', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
