# Generated by Django 3.2.5 on 2022-12-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0002_fileuploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
