# Generated by Django 3.2.5 on 2022-12-18 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordmodel',
            name='group',
            field=models.ManyToManyField(related_name='group_set', to='education.GroupModel'),
        ),
        migrations.AddField(
            model_name='recordmodel',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Spanish', 'Spanish'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic')], default='Bangla', max_length=35),
        ),
        migrations.AddField(
            model_name='recordmodel',
            name='subject',
            field=models.ManyToManyField(related_name='subject_set', to='education.SubjectModel'),
        ),
        migrations.AlterField(
            model_name='recordmodel',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recordmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recordmodel',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('clas', models.CharField(max_length=10)),
                ('roll', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
