# Generated by Django 3.2.5 on 2022-12-24 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0002_auto_20221218_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordmodel',
            name='likes',
            field=models.ManyToManyField(related_name='record_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recordmodel',
            name='views',
            field=models.ManyToManyField(related_name='record_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
