# Generated by Django 3.2.5 on 2022-12-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20221224_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmodel',
            name='views',
            field=models.IntegerField(),
        ),
    ]
