# Generated by Django 3.2.5 on 2022-12-24 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0006_alter_recordmodel_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordmodel',
            name='views',
        ),
        migrations.AddField(
            model_name='recordmodel',
            name='views',
            field=models.ManyToManyField(related_name='record_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
