"""
Django settings for first_project project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR=os.path.join(BASE_DIR,'templates')
STATIC_DIR= os.path.join(BASE_DIR,'static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@n$)^zmv*w0)asuy(s8ki(ok)f9zweo8%+=wv4oh4*(_)@)*9h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False
ALLOWED_HOSTS = []

# JWT Settings



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'machine_learning',
    'data_analysis',
    'home_page',
    'api_response',
    'rest_framework',
    'rest_framework.authtoken',
    'Rest_Api',
    'mail_app',
    'users',
    'New_Api',
    'rest_framework_simplejwt',
    'captcha',
    'crispy_forms',
    'education',
    'multiselectfield',
    'notifications',
    'social_django',
    'corsheaders',     # May not need for api response data return for react.js
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
     # CORS
    'corsheaders.middleware.CorsMiddleware',    # need for api response for react.js
    'django.middleware.common.CommonMiddleware', # need for api response for react.js
]
CORS_ORIGIN_ALLOW_ALL =False  # need for api response for react.js
CORS_ORIGIN_WHITELIST = (    # May not need for api response for react.js
    'http://localhost:3000', 'http://localhost:3002', 'http://localhost:3003','http://localhost:3004',
)

ROOT_URLCONF = 'first_project.urls'

CRISPY_TEMPLATE_PACK="bootstrap4"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Rest_Api.context_processors.topicComment',
                'social_django.context_processors.backends',  
                'social_django.context_processors.login_redirect',
            ],
        },
    },
] 

WSGI_APPLICATION = 'first_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE ='Asia/Dhaka'    #'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [STATIC_DIR,]
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# My email sending variables
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com' # "smtp.khurshed.xyz"   # 
EMAIL_PORT= 587  # 25         #465  #  # gmail port : 587 
EMAIL_USE_TLS=True
EMAIL_HOST_USER='rifat.diet@gmail.com'  #'khurshedhasan71@gmail.com' #'mail@khurshed.xyz' # 
EMAIL_HOST_PASSWORD='zlstqcbboiveorfd' #'f p b s h h k b i f y q c h d d'   # 'Zarin_ayman_04' # mail@khurshed.xyz => 'ayman_zain' # 
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL='OTF Team <rifat.diet@gmail.com>'# <mail@khurshed.xyz>   # 

# @login_required setting url
LOGIN_URL='login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL='/users/user_profile/'

REST_FRAMEWORK={

    'DEFAULT_AUTHENTICATION_CLASSES' :[
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
       
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # pip install djangorestframework_simplejwt  => Successfully installed djangorestframework_simplejwt-5.2.2 pyjwt-2.6.0
        'rest_framework.authentication.TokenAuthentication',      # for 'rest_framework.authtoken' App => obtain_auth_token
        ],

    'DEFAULT_PERMISSION_CLASSES' :[
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
        ],
    

}
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GITHUB_KEY ='f8c083382be63908f070'
SOCIAL_AUTH_GITHUB_SECRET ='c0648de4d50178c80e5b1160829aaff97a1079b7'

 # Consumer Keys & secret
SOCIAL_AUTH_TWITTER_KEY = 'DAAhEFgqFROC63RjWPZBnSpzT'
SOCIAL_AUTH_TWITTER_SECRET ='ogYTLhlGeaRc2Hweyb6eoaM6mZC7dmmPVpsAI5wEVmD122GHV6'

  # Auth 2.0 Client ID and Client Secret
# = 'ZmlqRndHT09mLXVPM2NlZEFjWUc6MTpjaQ'
#SOCIAL_AUTH_TWITTER_SECRET ='0MvC8vC1uhJb4dlJ3jXf68Kh_RM6ialud17kIiU9VsrFlk4glt'

     # Authentication Access Token & access token secret
#SOCIAL_AUTH_TWITTER_KEY = '1292853119483670529-sXM9nfO7SGUWNBgSfrzGy3vuAx79t4'
#SOCIAL_AUTH_TWITTER_SECRET ='QvtKwBVJjk4QgT9hVobtqsXZ0a1bCg4Jui1Mzws7Dkzsn'

SOCIAL_AUTH_FACEBOOK_KEY = '553740756655078'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = 'e0a5b9a161ea062d2afd43d4e9abce9a' # App Secret

SOCIAL_AUTH_LOGIN_ERROR_URL = '/users/settings/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/users/settings/'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

SOCIAL_AUTH_URL_NAMESPACE = 'social'